on:
  push:
    tags:
      - '*'
name: Cargo publish
jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish'
    # Reference your environment variables
    environment: cargo

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            args: --no-verify
            override: true
      - uses: katyo/publish-crates@v2
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}